// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtvXegJf1YUI38YidOuhqhXNXdnuMKgZo',
    appId: '1:1009251989487:web:720084cb88eeae50e3281a',
    messagingSenderId: '1009251989487',
    projectId: 'fir-app-a1323',
    authDomain: 'fir-app-a1323.firebaseapp.com',
    storageBucket: 'fir-app-a1323.firebasestorage.app',
    measurementId: 'G-TR9353ST1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ9ajetd5QMld81VRUWsHJZfclqKf1-NM',
    appId: '1:1009251989487:android:eed641a35c87bca7e3281a',
    messagingSenderId: '1009251989487',
    projectId: 'fir-app-a1323',
    storageBucket: 'fir-app-a1323.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIDb2zTdJ-znTiQCpRSUq3iET6gi7jnoc',
    appId: '1:1009251989487:ios:6dbb968b3788b195e3281a',
    messagingSenderId: '1009251989487',
    projectId: 'fir-app-a1323',
    storageBucket: 'fir-app-a1323.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIDb2zTdJ-znTiQCpRSUq3iET6gi7jnoc',
    appId: '1:1009251989487:ios:6dbb968b3788b195e3281a',
    messagingSenderId: '1009251989487',
    projectId: 'fir-app-a1323',
    storageBucket: 'fir-app-a1323.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtvXegJf1YUI38YidOuhqhXNXdnuMKgZo',
    appId: '1:1009251989487:web:ab14bc950bf6018ae3281a',
    messagingSenderId: '1009251989487',
    projectId: 'fir-app-a1323',
    authDomain: 'fir-app-a1323.firebaseapp.com',
    storageBucket: 'fir-app-a1323.firebasestorage.app',
    measurementId: 'G-77V5C2Y1HZ',
  );
}
